kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: mediawiki
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
      - name: mediawiki
        image: mediawiki
        ports:
        - containerPort: 80
