kind: Service
apiVersion: v1
metadata:
  name: mediawiki
spec:
  selector:
    app: mediawiki
  type: LoadBalancer
  ports:
    - name: mediawiki
      port: 8080
      targetPort: 80
      nodePort: 30001
